export type ContactLocale = 'nl' | 'en';

export const contactFormCopy = {
  nl: {
    progress: ['Behoefte', 'Context', 'Gegevens'],
    projectLegend: 'Wat wilt u realiseren?',
    goalLabel: 'Wat is de belangrijkste uitkomst?',
    goalHelp: 'Beschrijf de bottleneck of het concrete doel.',
    goalLimit: 'Maximaal 1.500 tekens.',
    goalPlaceholder: 'Beschrijf uw uitdaging…',
    companyLabel: 'Bedrijfsnaam',
    companyPlaceholder: 'Uw organisatie',
    budgetLabel: 'Beschikbaar budget',
    budgetPlaceholder: 'Selecteer een budgetindicatie',
    timelineLegend: 'Gewenste tijdlijn',
    nameLabel: 'Uw naam',
    namePlaceholder: 'Hoe mag ik u noemen?',
    nameLimit: 'Maximaal 100 tekens.',
    emailLabel: 'E-mailadres',
    phoneLabel: 'Telefoonnummer',
    phonePlaceholder: 'Optioneel',
    privacy: 'Ik gebruik deze gegevens alleen om contact met u op te nemen voor de intake.',
    back: 'Terug',
    next: 'Volgende stap',
    submit: 'Aanvraag versturen',
    submitting: 'Verzenden…',
    error: 'Er is iets misgegaan. Probeer het later opnieuw.',
    successTitle: 'Aanvraag ontvangen',
    successBody: 'Bedankt. Ik neem binnen 24 uur op werkdagen contact met u op.',
    projectTypes: [
      'IT Advies & Consultancy',
      'AI & Automatisering',
      'Maatwerk Platform / App',
      'IoT & Monitoring',
      'Anders',
    ],
    budgets: [
      '< €3.000 (oriënterend / low-code)',
      '€3.000 – €5.000',
      '€5.000 – €10.000',
      '€10.000+',
    ],
    timelines: ['Zo snel mogelijk', 'Binnen 3 maanden', 'Oriënterend (lange termijn)'],
  },
  en: {
    progress: ['Needs', 'Context', 'Details'],
    projectLegend: 'What would you like to build?',
    goalLabel: 'What is the most important outcome?',
    goalHelp: 'Describe the bottleneck or concrete goal.',
    goalLimit: 'Maximum 1,500 characters.',
    goalPlaceholder: 'Describe your challenge…',
    companyLabel: 'Company name',
    companyPlaceholder: 'Your organisation',
    budgetLabel: 'Available budget',
    budgetPlaceholder: 'Select a budget range',
    timelineLegend: 'Preferred timeline',
    nameLabel: 'Your name',
    namePlaceholder: 'How may I address you?',
    nameLimit: 'Maximum 100 characters.',
    emailLabel: 'Email address',
    phoneLabel: 'Phone number',
    phonePlaceholder: 'Optional',
    privacy: 'I only use these details to contact you about this intake.',
    back: 'Back',
    next: 'Next step',
    submit: 'Send request',
    submitting: 'Sending…',
    error: 'Something went wrong. Please try again later.',
    successTitle: 'Request received',
    successBody: 'Thank you. I will contact you within 24 hours on business days.',
    projectTypes: [
      'IT Advice & Consultancy',
      'AI & Automation',
      'Custom Platform / App',
      'IoT & Monitoring',
      'Other',
    ],
    budgets: [
      '< €3,000 (exploration / low-code)',
      '€3,000 – €5,000',
      '€5,000 – €10,000',
      '€10,000+',
    ],
    timelines: ['As soon as possible', 'Within 3 months', 'Exploring (long term)'],
  },
} as const;
